---
# tasks file for aquarium

# À FAIRE : désactiver les conteneurs si nécessaire

- name: "Configurer le parefeu (ufw)"
  include: configurer_parefeu.yml

- name: "Configurer le serveur mandataire (nginx)"
  include: configurer_mandataire.yml

- name: "Ajouter l'utilisateur Unix qui exécutera docker/docker-compose"
  user:
    name: "{{ utilisateur_unix }}"
    groups: docker
    append: yes
    generate_ssh_key: yes
    shell: /bin/bash
    #umask: '077' added in 2.12 of Ansible
  register: utilisateur_unix_cree
  become: yes

- name: "Sécuriser le répertoire de l'utilisateur Unix qui exécutera docker/docker-compose"
  file:
    path: "/home/{{ utilisateur_unix }}"
    state: directory
    mode: "u=rwX,g=rX,o="
  become: yes

- name: "Ajouter github.com aux known_hosts de l'utilisateur unix"
  known_hosts:
    name: github.com
    key: github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=
    path: "/home/{{ utilisateur_unix }}/.ssh/known_hosts"
    state: present
  become: yes
  become_user: "{{ utilisateur_unix }}"

# Ajouter la nouvelle clé SSH publique de utilisateur_unix à Github.com en ligne de commande.
# Il y a des exemples ici : https://unix.stackexchange.com/questions/136894/command-line-method-or-programmatically-add-ssh-key-to-github-com-user-account
# Pas prioritaire car le dépôt sera bientôt public.

- name: "Cloner le dépôt git de l'Aquarium"
  git:
    repo: "{{ depot_git_distant }}"
    dest: "/home/{{ utilisateur_unix }}/{{ depot_git_local }}"
    version: "{{ depot_git_version }}"
    force: yes
    recursive: yes
  become: yes
  become_user: "{{ utilisateur_unix }}"

- name: "S'assurer que le sous-module Jitsi est à la bonne version"
  shell:
    cmd: "git checkout -f {{ jitsi_version }}"
  args:
    chdir: "/home/{{ utilisateur_unix }}/{{ depot_git_local }}/jitsi"
    executable: /bin/bash
  become: yes
  become_user: "{{ utilisateur_unix }}"

- name: "Ajouter les répertoires de configuration nécessaires à l'Aquarium et Jitsi Meet"
  file:
    path: "{{ item }}"
    state: directory
  loop: "{{ repertoires_config }}"
  become: yes
  become_user: "{{ utilisateur_unix }}"

- name: "Copier tous les fichiers de config. de l'Aquarium et de Jitsi Meet"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ utilisateur_unix }}"
    mode: "{{ item.mode }}"
  loop:
    - { src: "Dockerfile.j2", dest: "/home/{{ utilisateur_unix }}/{{ depot_git_local }}/Dockerfile", owner: "{{ utilisateur_unix }}", mode: "0640" }
    - { src: "init_db.sql.j2", dest: "/home/{{ utilisateur_unix }}/{{ depot_git_local }}/docker-compose/mysql/init_db.sql", owner: "{{ utilisateur_unix }}", mode: "0640" }
    - { src: "custom.cnf.j2", dest: "/home/{{ utilisateur_unix }}/{{ depot_git_local }}/docker-compose/mysql-conf.d/custom.cnf", owner: "{{ utilisateur_unix }}", mode: "0640" }
    - { src: "docker-compose-prod.yml.j2", dest: "/home/{{ utilisateur_unix }}/{{ depot_git_local }}/docker-compose-prod.yml", owner: "{{ utilisateur_unix }}", mode: "0640" }
    - { src: "docker-compose-jitsi.yml.j2", dest: "/home/{{ utilisateur_unix }}/{{ depot_git_local }}/jitsi/docker-compose.yml", owner: "{{ utilisateur_unix }}", mode: "0640" }
    - { src: "env-prod.j2", dest: "/home/{{ utilisateur_unix }}/{{ depot_git_local }}/.env", owner: "{{ utilisateur_unix }}", mode: "0640" }
    - { src: "sauv-db.sh.j2", dest: "/home/{{ utilisateur_unix }}/{{ depot_git_local }}/sauv-db.sh", owner: "{{ utilisateur_unix }}", mode: "0740" }
    - { src: "aquarium.conf.j2", dest: "/home/{{ utilisateur_unix }}/{{ depot_git_local }}/docker-compose/nginx/conf.d/aquarium.conf", owner: "{{ utilisateur_unix }}", mode: "0640" }
    - { src: "Dockerfile-aquarium-nginx.j2", dest: "/home/{{ utilisateur_unix }}/{{ depot_git_local }}/docker-compose/nginx/Dockerfile", owner: "{{ utilisateur_unix }}", mode: "0640" }
    - { src: "opcache.ini.j2", dest: "/home/{{ utilisateur_unix }}/{{ depot_git_local }}/docker-compose/php/opcache.ini", owner: "{{ utilisateur_unix }}", mode: "0640" }
    - { src: "php.ini.production.j2", dest: "/home/{{ utilisateur_unix }}/{{ depot_git_local }}/docker-compose/php/php.ini", owner: "{{ utilisateur_unix }}", mode: "0640" }
    - { src: "security.ini.j2", dest: "/home/{{ utilisateur_unix }}/{{ depot_git_local }}/docker-compose/php/security.ini", owner: "{{ utilisateur_unix }}", mode: "0640" }
    - { src: "dockerignore.j2", dest: "/home/{{ utilisateur_unix }}/{{ depot_git_local }}/.dockerignore", owner: "{{ utilisateur_unix }}", mode: "0640" }
    - { src: "prosody.cfg.lua.j2", dest: "/home/{{ utilisateur_unix }}/{{ depot_git_local }}/jitsi/prosody/rootfs/defaults/prosody.cfg.lua", owner: "{{ utilisateur_unix }}", mode: "0640" }
    #- { src: "jitsi-meet.cfg.lua.j2", dest: "/home/{{ utilisateur_unix }}/{{ depot_git_local }}/jitsi/prosody/rootfs/defaults/conf.d/jitsi-meet.cfg.lua", owner: "{{ utilisateur_unix }}", mode: "0640" }
    #- { src: "mod_muc_status.lua.j2", dest: "/home/{{ utilisateur_unix }}/.jitsi-meet-cfg/prosody/prosody-plugins-custom/mod_muc_status.lua", owner: "{{ utilisateur_unix }}", mode: "0644" }
    - { src: "meet.conf.j2", dest: "/home/{{ utilisateur_unix }}/{{ depot_git_local }}/jitsi/web/rootfs/defaults/meet.conf", owner: "{{ utilisateur_unix }}", mode: "0644" }
    - { src: "Dockerfile-aquarium-phpmyadmin.j2", dest: "/home/{{ utilisateur_unix }}/{{ depot_git_local }}/docker-compose/phpmyadmin/Dockerfile", owner: "{{ utilisateur_unix }}", mode: "0644" }
    - { src: "config.user.inc.php.j2", dest: "/home/{{ utilisateur_unix }}/{{ depot_git_local }}/docker-compose/phpmyadmin/config.user.inc.php", owner: "{{ utilisateur_unix }}", mode: "0640" }
  become: yes

- name: "Se connecter à Docker Hub"
  docker_login:
    username: "{{ docker_hub_nom }}"
    password: "{{ docker_hub_mdp }}"
  become: yes
  become_user: "{{ utilisateur_unix }}"

- name: "Désactiver tous les services via docker-compose"
  command: docker-compose -f docker-compose-prod.yml -f jitsi/docker-compose.yml down --remove-orphans
  args:
    chdir: /home/{{ utilisateur_unix }}/{{ depot_git_local }}
  become: yes
  become_user: "{{ utilisateur_unix }}"
  ignore_errors: yes

- name: "(Re)démarrer tous les services de L'Aquarium + Jitsi Meet via docker-compose"
  command: docker-compose -f docker-compose-prod.yml -f jitsi/docker-compose.yml up -d --build
  args:
    chdir: /home/{{ utilisateur_unix }}/{{ depot_git_local }}
  become: yes
  become_user: "{{ utilisateur_unix }}"

- name: "Installer les dép. php/nodejs de l'Aquarium, générer une clé avec artisan, activer le cache, etc."
  shell:
    cmd: "{{ item }}"
  args:
    chdir: /home/{{ utilisateur_unix }}/{{ depot_git_local }}
    executable: /bin/bash
  loop:
    - docker-compose exec -T app composer install --optimize-autoloader --no-dev
    - docker-compose exec -T app npm install
    - docker-compose exec -T app npm run production
    - docker-compose exec -T app npm prune --production
    - docker-compose exec -T app php artisan key:generate
    - docker-compose exec -T app php artisan storage:link
    - docker-compose exec -T app php artisan config:cache
    #- docker-compose exec -T app php artisan route:cache
    - docker-compose exec -T app php artisan view:cache
  become: yes
  become_user: "{{ utilisateur_unix }}"

- name: "Se déconnecter de Docker Hub"
  docker_login:
    state: absent
  become: yes
  become_user: "{{ utilisateur_unix }}"

- name: "Programmer la sauv. auto. de la BD"
  cron:
    name: "Sauvegarde BD"
    user: "{{ utilisateur_unix }}"
    minute: "0"
    hour: "3"
    job: "/home/{{ utilisateur_unix }}/{{ depot_git_local }}/sauv-db.sh"
  become: yes
