FROM php:7.4-fpm

# Arguments defined in docker-compose.yml
ARG user
ARG uid

# Install system dependencies
RUN apt-get update && apt-get install -y \
    libzip-dev \
    git \
    libpng-dev \
    libfreetype6-dev \
    libjpeg62-turbo-dev

# Install nodejs
RUN curl -fsSL https://deb.nodesource.com/setup_14.x | bash - \
    && apt-get install -y nodejs

# Clear cache
RUN apt-get autoremove -y && apt-get clean && rm -rf /var/lib/apt/lists/*

# Install and configure PHP extensions
RUN docker-php-ext-configure opcache --enable-opcache \
    && docker-php-ext-configure gd \
    && docker-php-ext-install -j$(nproc) pdo_mysql gd zip opcache

RUN pecl install -o -f redis \
    &&  rm -rf /tmp/pear \
    &&  docker-php-ext-enable redis

# Get latest Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Create system user to run Composer and Artisan Commands
RUN useradd -G www-data,root -u $uid -d /home/$user $user
RUN mkdir -p /home/$user/.composer && \
    chown -R $user:$user /home/$user


RUN docker-php-ext-install sockets
# Set working directory
WORKDIR /var/www/aquarium

USER $user

EXPOSE 6001

CMD ["php", "artisan", "websockets:serve"]

